env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "UrnVb9FES2MRus3FklvBmxre7E2EAmA9Xdco3Sp2dLTPaKvxgJpYQ5WOc9Q320pdKK4XVguvemh1hFa5V6DPOOjcWH3BG+ohSgwRRqHcxAGgfT8qhuxTQnA1CQn8QM/n2Ha8P3jggUIghYocb6I+tuPTMO6HtbNurzrfVxNFIs0="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

os:
 - linux
 - osx

matrix:
  allow_failures:
    - os: osx

# run tests
script: tests/do_tests.bash

addons:
  coverity_scan:
    project:
      name: "superna9999/pyfdt"
      description: "Build submitted via Travis CI"
    notification_email: superna9999@gmail.com
    build_command_prepend: ""
    build_command:   ""
    branch_pattern: coverity_scan
